// src/components/PostStats.svelte
<script lang="ts">
    import { onMount } from "svelte";

    export let slug: string = ''

    let loading: boolean = false
    let views: number = 0

    onMount(async () => {
        if(slug && slug.trim() !== '') {
            try {
                loading = true
                const resp = await fetch(`/api/blog/views/${slug}.json`)
                const stats = await resp.json()
                views = stats.views
            } catch(e) {
                console.error('PostStats', e)
            } finally {
                loading = false
            }
        }
    })
</script>
<span class="emdash">—</span>
<span class="post-stats__views">{ views } views</span>
<style>
    .post-stats__views {
        @apply pr-1 mx-1 italic text-accent-gray-mid;
    }
</style>

// src/components/react/PostStats.tsx
import { Fragment, useEffect, useState } from "react";
import { saveError } from "~services/api";

const PostStats = ({ slug }: { slug: string }) => {
  const [isLoading, setIsLoading] = useState(false);
  const [views, setViews] = useState();

  useEffect(() => {
    const fetchData = async () => {
      try {
        const resp = await fetch(`/api/blog/views/${slug}.json`);
        const stat = await resp.json();
        setViews(stat.numViews);
      } catch (e) {
        if (import.meta.env.DEV) {
          console.error("Error fetching post views", e);
        }
        saveError(e as Error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchData();
  }, [slug]);

  return (
    <Fragment>
      <span className="emdash">—</span>
      <span className="pr-1 mx-1 italic text-muted-light">
        {views || "~"} views
      </span>
    </Fragment>
  );
};
export default PostStats;
